# Generated by Django 4.1.3 on 2023-04-27 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('pid', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('parentname', models.CharField(blank=True, db_column='ParentName', max_length=25, null=True)),
                ('rollno', models.CharField(blank=True, db_column='RollNo', max_length=15, null=True)),
                ('studentname', models.CharField(blank=True, db_column='StudentName', max_length=25, null=True)),
                ('phonenum', models.BigIntegerField(blank=True, db_column='PhoneNum', null=True)),
                ('standard', models.CharField(blank=True, db_column='Standard', max_length=3, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=2, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=25, null=True)),
            ],
            options={
                'db_table': 'parents',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('tid', models.CharField(max_length=3, primary_key=True, serialize=False)),
                ('teacherName', models.CharField(max_length=25)),
                ('Class', models.CharField(max_length=2)),
                ('section', models.CharField(max_length=1)),
                ('password', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='TeacherParent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduapp.parents')),
                ('tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduapp.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('absentDate', models.DateField()),
                ('Class', models.CharField(max_length=2)),
                ('section', models.CharField(max_length=1)),
                ('rollNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduapp.parents')),
            ],
        ),
        migrations.CreateModel(
            name='ApplyLeave',
            fields=[
                ('lid', models.AutoField(primary_key=True, serialize=False)),
                ('fromDate', models.DateField()),
                ('toDate', models.DateField()),
                ('reason', models.TextField()),
                ('rollNo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eduapp.parents')),
            ],
        ),
    ]
