# Generated by Django 4.1.3 on 2023-05-06 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Parents',
            fields=[
                ('pid', models.AutoField(db_column='PID', primary_key=True, serialize=False)),
                ('parentname', models.CharField(blank=True, db_column='ParentName', max_length=25, null=True)),
                ('rollno', models.CharField(blank=True, db_column='RollNo', max_length=15, null=True)),
                ('studentname', models.CharField(blank=True, db_column='StudentName', max_length=25, null=True)),
                ('phonenum', models.BigIntegerField(blank=True, db_column='PhoneNum', null=True)),
                ('standard', models.CharField(blank=True, db_column='Standard', max_length=3, null=True)),
                ('section', models.CharField(blank=True, db_column='Section', max_length=2, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=50, null=True)),
                ('password', models.CharField(blank=True, db_column='Password', max_length=25, null=True)),
            ],
            options={
                'db_table': 'parents',
                'managed': False,
            },
        ),
    ]
